### ISSUE TITLE
chat history clear request

### ISSUE THREAD

**Issue by niansa** [ircv3/ircv3-ideas#25]
A request which can be send to another user:

`/clearreq <user> <#channel> <description>`

In \<user\>s client a window will be opend: `*** wants that you clear your chat history in <#channel> because <description>.`

Additionaly a system to only allow requests from specified client or to not allow requests from specified client.

**Comment by DanielOaks** [comment]
Hmm, honestly I don't see too much value in having a command like this, delivers the same thing as just sending the user a privmsg asking them to do it. Issue #21 has a specific metadata key that's aimed to prevent the logging in the first place, in a more automated way.

**Comment by niansa** [comment]
I don't mean that. As example if someone wrote something bad and the channel moderators do not want a specific user to read this as example because the specific user is underage and should not read that. :-)

**Comment by realJoshByrnes** [comment]
I for one, wouldn't like to clear my chat history because someone has chosen to mask a prohibited word/phrase.

However, with message IDs, it would be absolutely possible to mask messages.
`REDACT <context> <MessageID> [bytes]`.
If bytes is omitted, the whole line should be redacted.
If bytes is provided, only part of the text should be removed, although it would be important to establish how this should be treated with wide characters etc. I'd probably even suggest using ASCII to specify it.

A client could instead show "Message hidden by <name>" or similar.

**Comment by sadiepowell** [comment]
> I for one, wouldn't like to clear my chat history because someone has chosen to mask a prohibited word/phrase.
> 
> However, with message IDs, it would be absolutely possible to mask messages.
> `REDACT <context> <MessageID> [bytes]`.
> If bytes is omitted, the whole line should be redacted.
> If bytes is provided, only part of the text should be removed, although it would be important to establish how this should be treated with wide characters etc. I'd probably even suggest using ASCII to specify it.
> 
> A client could instead show "Message hidden by " or similar.

This sounds like message deletion which is proposed at https://github.com/ircv3/ircv3-specifications/pull/304.
