### ISSUE TITLE
Messages with images

### ISSUE THREAD

**Issue by DanielOaks** [ircv3/ircv3-ideas#4]
With Slack and such, you can drag an image into your client and it'll upload to Slack for everyone else to see.

Similar functionality would be nice to have for IRC clients that wish to use it. Here are some proposed ideas:
- IRCd provides the client with an endpoint to upload images and such to. This may also be extendable to other types of files if we're already implementing it this way, and seems like the best way to go about this in my eyes. Essentially, allowing similar interactions to the way IRCCloud does it.
- Providing them directly in-line, encoded. This won't fly, since message lengths and having to send 100 messages to get an image across.
- Providing them directly to clients in some sort of a dcc-like system. Interesting theoretically, but a massive pain to actually implement and I can see it being fraught with issues so I think this idea is best binned.

@dequis posted this, and it's essentially along the lines of what I was thinking for the best way to approach it:

---

> Using an external protocol complicates stuff.. new ports to open (NAT/firewall issues) sync with another service/process supplying that protocol.

If this is your main concern, there are two ports that are available practically everywhere: 80 and 443.

My idea of an out of band implementation of upload would be the ircd providing a http(s) url, optionally with user/session/channel specific GET parameters (for any required rate limiting), which can be accessed directly by the user (showing an html page) or can be POSTed directly by the irc client with `multipart/form-data` with predefined field names, and returns the result in an easily parseable format - which, if no extra information is needed, may be just a `302 Found` redirect with the image URL in the `Location` header and the plaintext body.

**Comment by DanielOaks** [comment]
I should add, the main mark against a proposal like that is that it may not work with public IRC nets. For this sort of workflow I'd imagine some fallback solutions (such as falling back to other public image upload services) for clients that want to implement them.

**Comment by jwheare** [comment]
This is one of those things that is more about infrastructure than protocol. _All_ of the hosted services mentioned that allow image uploads do so through an http endpoint to a service that is external to their main chat protocol. They just happen to control both the chat service and the image hosting service so it's easy to integrate. IRCCloud file uploads work the same way. 

This working group is primarily about defining features within the existing IRC protocol. As this suggestion involves using a separate protocol and separate infrastructure it's pretty much out of scope.

Of course, it's already possible for a client to integrate with any public image hosting service, for easy uploading and embedding, and several do. Imgur has an API and there are a few ui libraries out there that provide a standard interface for embedding and uploading to multiple services.

Any desire to standardise an interface for uploading to any image host is frought with issues, because different hosts have different requirements of scaling, production environment, authentication, load balancing, programming language.

I don't think it's feasible for IRCv3 to tackle this issue.

**Comment by lollipopman** [comment]
> I don't think it's feasible for IRCv3 to tackle this issue.

@jwheare would the IRCv3 batch extension open up the possibility of encoding images or other data inline?

**Comment by jwheare** [comment]
I still don't think sending image data in band is workable.
